const sqlite3 = require('sqlite3').verbose();

const db = new sqlite3.Database('applicant.db');

// Drop table if exists and then recreate it
db.serialize(() => {
    db.run(`DROP TABLE IF EXISTS applicant`);
    db.run(`CREATE TABLE applicant (
        appl_no INTEGER NOT NULL UNIQUE,
        appl_date TEXT NOT NULL,
        name TEXT,
        gender TEXT,
        materialStatus TEXT,
        educationQualification TEXT,
        email TEXT,
        dateOfBirth TEXT,
        phoneNumber TEXT,
        whatsappNumber TEXT,
        isWhatsapp TEXT,
        father TEXT,
        mother TEXT,
        occupation TEXT,
        designation TEXT,
        natureOfDuties TEXT,
        presentEmployer TEXT,
        lengthOfServiceBusiness TEXT,
        workLocation TEXT,
        annualIncome INTEGER,
        panCardNumber TEXT,
        aadhaarNumber TEXT,
        currentAddress TEXT,
        sameAddress TEXT,
        permanentAddress TEXT,
        pinCode TEXT,
        city TEXT,
        state TEXT,
        country TEXT,
        landmark TEXT,
        foreignNational TEXT,
        pepStatus TEXT,
        bankName TEXT,
        accountNumber TEXT,
        MICR TEXT,
        ifscCode TEXT,
        accountType TEXT,
        branchAddress TEXT,
        nomineeName TEXT,
        nomineeDOB TEXT,
        nomineeGender TEXT,
        nomineeRelationship TEXT,
        nomineePhoneNumber TEXT,
        appointeeName TEXT,
        appointeeRelationship TEXT,
        paymentMode TEXT,  
        planSelection TEXT,
        subscriptionOption TEXT,
        payor_name TEXT,
        payor_relation TEXT,
        payor_phone TEXT,
        payor_email TEXT,
        opt_option TEXT,
        with_name TEXT,
        with_relationship TEXT,
        with_address TEXT,
        with_city TEXT,
        with_state TEXT,
        with_country TEXT,
        with_pincode TEXT,
        with_landmark TEXT,
        terms_accepted BOOLEAN
    )`);
});

module.exports = db;
